import type { ApiConfig } from "../src/config.ts";

/** Full `ApiConfig` for route/service unit tests (no missing keys after env changes). */
export function createTestApiConfig(overrides: Partial<ApiConfig> = {}): ApiConfig {
  return {
    nodeEnv: "test",
    port: 4000,
    logLevel: "debug",
    corsOrigin: "*",
    databaseUrl: "",
    redisUrl: "",
    authCodeTtlSeconds: 300,
    authResendCooldownSeconds: 60,
    authCodeMaxAttempts: 5,
    authRateLimitWindowSeconds: 600,
    authRateLimitStartPerEmail: 5,
    authRateLimitStartPerIp: 10,
    authRateLimitConfirmPerIp: 30,
    authRateLimitResendPerIp: 10,
    registrationAuthStateTtlSeconds: 3600,
    registrationResultTtlSeconds: 604800,
    deviceApprovalTtlSeconds: 600,
    sessionSecret: "test-session-secret-key-min-32-chars",
    sessionTtlSeconds: 3600,
    authPendingTwoFactorTtlSeconds: 600,
    totpEnrollmentTtlSeconds: 600,
    twoFactorVerifyMaxAttemptsPerState: 5,
    twoFactorVerifyClockSteps: 1,
    authRateLimitTwoFactorVerifyPerIp: 40,
    twoFactorBackupCodesCount: 10,
    allowHeaderUserIdAuth: true,
    defaultEmailLocale: "en",
    emailFrom: "no-reply@okkey.local",
    emailProvider: "logger",
    smtpHost: "localhost",
    smtpPort: 1025,
    smtpSecure: false,
    smtpUser: "",
    smtpPassword: "",
    emailApiEndpoint: "",
    emailApiKey: "",
    emailApiTimeoutMs: 10_000,
    ...overrides,
  };
}
