/** Re-export shared device environment helpers (source of truth: `@okkey/ui`). */
export {
  buildDefaultDeviceName,
  buildDeviceFingerprintId,
  formatClientLabelFromType,
  formatDeviceChannel,
  formatDeviceClientOs,
  formatDeviceTitle,
  isAutoGeneratedDeviceTitle,
  parseBrowserEnvironment,
  parseOsFromDeviceName,
  type BrowserClientId,
  type DeviceChannel,
  type DeviceDisplayHints,
  type ParseBrowserEnvironmentOptions,
  type ParsedBrowserEnvironment,
} from "@okkey/ui";
