// Generated by scripts/gen-web-bundles.mjs — do not edit by hand.

import en from "./locales/web/en.json" with { type: "json" };
import ru from "./locales/web/ru.json" with { type: "json" };

export const webBundles = {
  en,
  ru,
} as const;

export type WebLocale = keyof typeof webBundles;

export const WEB_LOCALES = Object.keys(webBundles) as WebLocale[];

